[project]
name = "notebooktester"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "raoul grouls", email = "Raoul.Grouls@han.nl" }
]
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "loguru>=0.7.3",
]

[project.scripts]
notebooktester = "notebooktester.cli:run_tests"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
